packages:
  - apps/api
  - apps/website
  - packages/shared/database

catalog:
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  hono: ^4.11.1
  wrangler: ^4.40.3
  zod: ^4.1.13

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
