name = "shibes-lol"
compatibility_flags = ["nodejs_als"]
compatibility_date = "2024-05-12"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "APP_DB"                                   # i.e. available in your Worker on env.APP_DB
database_name = "shibes-lol-db"
database_id = "3b4d9d21-3011-40be-b724-f30c361df4b3"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = 'APP_BUCKET'
bucket_name = 'shibes-lol-bucket'
