/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyShibasRouteImport } from './routes/my-shibas'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShibeImgRefRouteImport } from './routes/shibe/$imgRef'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminShibasRouteImport } from './routes/admin/shibas'
import { Route as AdminLayoutRouteImport } from './routes/admin/layout'
import { Route as ApiUploadRouteRouteImport } from './routes/api/upload/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const MyShibasRoute = MyShibasRouteImport.update({
  id: '/my-shibas',
  path: '/my-shibas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShibeImgRefRoute = ShibeImgRefRouteImport.update({
  id: '/shibe/$imgRef',
  path: '/shibe/$imgRef',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShibasRoute = AdminShibasRouteImport.update({
  id: '/admin/shibas',
  path: '/admin/shibas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/layout',
  path: '/admin/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRouteRoute = ApiUploadRouteRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/my-shibas': typeof MyShibasRoute
  '/api/upload': typeof ApiUploadRouteRoute
  '/admin/layout': typeof AdminLayoutRoute
  '/admin/shibas': typeof AdminShibasRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/shibe/$imgRef': typeof ShibeImgRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/my-shibas': typeof MyShibasRoute
  '/api/upload': typeof ApiUploadRouteRoute
  '/admin/layout': typeof AdminLayoutRoute
  '/admin/shibas': typeof AdminShibasRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/shibe/$imgRef': typeof ShibeImgRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/my-shibas': typeof MyShibasRoute
  '/api/upload': typeof ApiUploadRouteRoute
  '/admin/layout': typeof AdminLayoutRoute
  '/admin/shibas': typeof AdminShibasRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/shibe/$imgRef': typeof ShibeImgRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/my-shibas'
    | '/api/upload'
    | '/admin/layout'
    | '/admin/shibas'
    | '/admin/stats'
    | '/admin/users'
    | '/shibe/$imgRef'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/my-shibas'
    | '/api/upload'
    | '/admin/layout'
    | '/admin/shibas'
    | '/admin/stats'
    | '/admin/users'
    | '/shibe/$imgRef'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/my-shibas'
    | '/api/upload'
    | '/admin/layout'
    | '/admin/shibas'
    | '/admin/stats'
    | '/admin/users'
    | '/shibe/$imgRef'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  MyShibasRoute: typeof MyShibasRoute
  ApiUploadRouteRoute: typeof ApiUploadRouteRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminShibasRoute: typeof AdminShibasRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ShibeImgRefRoute: typeof ShibeImgRefRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-shibas': {
      id: '/my-shibas'
      path: '/my-shibas'
      fullPath: '/my-shibas'
      preLoaderRoute: typeof MyShibasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shibe/$imgRef': {
      id: '/shibe/$imgRef'
      path: '/shibe/$imgRef'
      fullPath: '/shibe/$imgRef'
      preLoaderRoute: typeof ShibeImgRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shibas': {
      id: '/admin/shibas'
      path: '/admin/shibas'
      fullPath: '/admin/shibas'
      preLoaderRoute: typeof AdminShibasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/layout': {
      id: '/admin/layout'
      path: '/admin/layout'
      fullPath: '/admin/layout'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  MyShibasRoute: MyShibasRoute,
  ApiUploadRouteRoute: ApiUploadRouteRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminShibasRoute: AdminShibasRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ShibeImgRefRoute: ShibeImgRefRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
