/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyShibasRouteImport } from './routes/my-shibas'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShibeImgRefRouteImport } from './routes/shibe/$imgRef'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const MyShibasRoute = MyShibasRouteImport.update({
  id: '/my-shibas',
  path: '/my-shibas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShibeImgRefRoute = ShibeImgRefRouteImport.update({
  id: '/shibe/$imgRef',
  path: '/shibe/$imgRef',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/my-shibas': typeof MyShibasRoute
  '/shibe/$imgRef': typeof ShibeImgRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/my-shibas': typeof MyShibasRoute
  '/shibe/$imgRef': typeof ShibeImgRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/my-shibas': typeof MyShibasRoute
  '/shibe/$imgRef': typeof ShibeImgRefRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/my-shibas'
    | '/shibe/$imgRef'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/my-shibas' | '/shibe/$imgRef' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/my-shibas'
    | '/shibe/$imgRef'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  MyShibasRoute: typeof MyShibasRoute
  ShibeImgRefRoute: typeof ShibeImgRefRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-shibas': {
      id: '/my-shibas'
      path: '/my-shibas'
      fullPath: '/my-shibas'
      preLoaderRoute: typeof MyShibasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shibe/$imgRef': {
      id: '/shibe/$imgRef'
      path: '/shibe/$imgRef'
      fullPath: '/shibe/$imgRef'
      preLoaderRoute: typeof ShibeImgRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  MyShibasRoute: MyShibasRoute,
  ShibeImgRefRoute: ShibeImgRefRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
